@MedicalCenterApi_HostAddress = https://localhost:7285
@env = https://localhost:7285

###
GET {{env}}/api/doctor
###

GET {{env}}/api/doctor/1

###

POST {{env}}/api/doctor
Content-Type: application/json

{
  "Name": "Ali Zafar",
  "Description": "General Physician",
  "Specialities": "Ffamily doctor"
}

###
